export const sampleTasks = [
  {
    title: 'Map onboarding drop-off points',
    description: 'Review the current activation funnel and identify where new teams stall.',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-10-12',
    assignee: 'Maya Chen',
    label: 'Research',
  },
  {
    title: 'Add keyboard navigation to command menu',
    description: 'Support arrow keys, escape, and focus restoration after selection.',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-10-15',
    assignee: 'Noah Kim',
    label: 'Accessibility',
  },
  {
    title: 'Instrument review completion events',
    description: 'Agree on the event schema before wiring it into the client.',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2026-10-10',
    assignee: 'Avery Patel',
    label: 'Analytics',
  },
  {
    title: 'Reduce dashboard table layout shift',
    description: 'Reserve space for asynchronous repository metadata.',
    status: 'in_progress',
    priority: 'low',
    dueDate: '2026-10-18',
    assignee: 'Maya Chen',
    label: 'Frontend',
  },
  {
    title: 'Document repository permission scopes',
    description: 'Explain read and write scopes in the installation flow.',
    status: 'done',
    priority: 'medium',
    dueDate: null,
    assignee: 'Noah Kim',
    label: 'Docs',
  },
  {
    title: 'Add retry guidance to failed reviews',
    description: 'Show an actionable retry message instead of a generic error.',
    status: 'done',
    priority: 'high',
    dueDate: '2026-10-08',
    assignee: 'Avery Patel',
    label: 'Reliability',
  },
];